//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.20 at 08:54:37 PM CET 
//


package proj.xmlws.UserModule.model.reservation;

import proj.xmlws.UserModule.model.accommodation.AccommodationUnit;
import proj.xmlws.UserModule.model.users.User;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="From_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="To_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Confirmed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Comment_rate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Comment" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Odobren" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="Sadrzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Rate">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Date_of_rate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Accommodation_unit"/>
 *         &lt;element name="Guest" type="{http://booking.uns.ac.rs/users}User"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/reservation}Message" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromDate",
    "toDate",
    "confirmed",
    "commentRate",
    "accommodationUnit",
    "guest",
    "id",
    "deleted",
    "messages"
})
@XmlRootElement(name = "Reservation")
@Entity
public class Reservation {

    @XmlElement(name = "From_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected LocalDate fromDate;

    @XmlElement(name = "To_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected LocalDate toDate;

    @XmlElement(name = "Confirmed")
    protected boolean confirmed;

    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(referencedColumnName = "id", nullable = true, unique = true)
    @XmlElement(name = "Comment_rate")
    protected CommentRate commentRate;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Accommodation_unit", namespace = "http://booking.uns.ac.rs/accommodation", required = true)
    protected AccommodationUnit accommodationUnit;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Guest", required = true)
    protected User guest;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlElement(name = "Id")
    protected long id;

    @XmlElement(name = "Deleted")
    protected boolean deleted;

    @OneToMany(mappedBy = "reservation", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Message", required = true)
    protected List<Message> messages;


    public Reservation() {

    }
    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public LocalDate getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(LocalDate value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public LocalDate getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setToDate(LocalDate value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the confirmed property.
     * 
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * Sets the value of the confirmed property.
     * 
     */
    public void setConfirmed(boolean value) {
        this.confirmed = value;
    }

    /**
     * Gets the value of the commentRate property.
     * 
     * @return
     *     possible object is
     *     {@link CommentRate }
     *     
     */
    public CommentRate getCommentRate() {
        return commentRate;
    }

    /**
     * Sets the value of the commentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentRate }
     *     
     */
    public void setCommentRate(CommentRate value) {
        this.commentRate = value;
    }

    /**
     * Gets the value of the accommodationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationUnit }
     *     
     */
    public AccommodationUnit getAccommodationUnit() {
        return accommodationUnit;
    }

    /**
     * Sets the value of the accommodationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationUnit }
     *     
     */
    public void setAccommodationUnit(AccommodationUnit value) {
        this.accommodationUnit = value;
    }

    /**
     * Gets the value of the guest property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getGuest() {
        return guest;
    }

    /**
     * Sets the value of the guest property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setGuest(User value) {
        this.guest = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessages() {
        if (messages == null) {
            messages = new ArrayList<Message>();
        }
        return this.messages;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Comment" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Odobren" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="Sadrzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Rate">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Date_of_rate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
//    @XmlAccessorType(XmlAccessType.FIELD)
//    @XmlType(name = "", propOrder = {
//        "comment",
//        "rate"
//    })
//    public static class CommentRate {
//
//        @XmlElement(name = "Comment")
//        protected Reservation.CommentRate.Comment comment;
//        @XmlElement(name = "Rate")
//        protected int rate;
//        @XmlAttribute(name = "Date_of_rate")
//        @XmlSchemaType(name = "dateTime")
//        protected XMLGregorianCalendar dateOfRate;
//
//        /**
//         * Gets the value of the comment property.
//         *
//         * @return
//         *     possible object is
//         *     {@link Reservation.CommentRate.Comment }
//         *
//         */
//        public Reservation.CommentRate.Comment getComment() {
//            return comment;
//        }
//
//        /**
//         * Sets the value of the comment property.
//         *
//         * @param value
//         *     allowed object is
//         *     {@link Reservation.CommentRate.Comment }
//         *
//         */
//        public void setComment(Reservation.CommentRate.Comment value) {
//            this.comment = value;
//        }
//
//        /**
//         * Gets the value of the rate property.
//         *
//         */
//        public int getRate() {
//            return rate;
//        }
//
//        /**
//         * Sets the value of the rate property.
//         *
//         */
//        public void setRate(int value) {
//            this.rate = value;
//        }
//
//        /**
//         * Gets the value of the dateOfRate property.
//         *
//         * @return
//         *     possible object is
//         *     {@link XMLGregorianCalendar }
//         *
//         */
//        public XMLGregorianCalendar getDateOfRate() {
//            return dateOfRate;
//        }
//
//        /**
//         * Sets the value of the dateOfRate property.
//         *
//         * @param value
//         *     allowed object is
//         *     {@link XMLGregorianCalendar }
//         *
//         */
//        public void setDateOfRate(XMLGregorianCalendar value) {
//            this.dateOfRate = value;
//        }
//
//
//        /**
//         * <p>Java class for anonymous complex type.
//         *
//         * <p>The following schema fragment specifies the expected content contained within this class.
//         *
//         * <pre>
//         * &lt;complexType>
//         *   &lt;complexContent>
//         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
//         *       &lt;attribute name="Odobren" type="{http://www.w3.org/2001/XMLSchema}boolean" />
//         *       &lt;attribute name="Sadrzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
//         *     &lt;/restriction>
//         *   &lt;/complexContent>
//         * &lt;/complexType>
//         * </pre>
//         *
//         *
//         */
//        @XmlAccessorType(XmlAccessType.FIELD)
//        @XmlType(name = "")
//        public static class Comment {
//
//            @XmlAttribute(name = "Odobren")
//            protected Boolean odobren;
//            @XmlAttribute(name = "Sadrzaj")
//            protected String sadrzaj;
//
//            /**
//             * Gets the value of the odobren property.
//             *
//             * @return
//             *     possible object is
//             *     {@link Boolean }
//             *
//             */
//            public Boolean isOdobren() {
//                return odobren;
//            }
//
//            /**
//             * Sets the value of the odobren property.
//             *
//             * @param value
//             *     allowed object is
//             *     {@link Boolean }
//             *
//             */
//            public void setOdobren(Boolean value) {
//                this.odobren = value;
//            }
//
//            /**
//             * Gets the value of the sadrzaj property.
//             *
//             * @return
//             *     possible object is
//             *     {@link String }
//             *
//             */
//            public String getSadrzaj() {
//                return sadrzaj;
//            }
//
//            /**
//             * Sets the value of the sadrzaj property.
//             *
//             * @param value
//             *     allowed object is
//             *     {@link String }
//             *
//             */
//            public void setSadrzaj(String value) {
//                this.sadrzaj = value;
//            }
//
//        }

//    }

}
