//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.20 at 08:54:37 PM CET 
//


package proj.xmlws.MessageModule.model.accommodation;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import proj.xmlws.MessageModule.model.reservation.Reservation;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import java.util.HashSet;
import java.util.Set;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Number_of_beds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Default_price" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Accommodation_unit_type"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Period_price" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Accommodation"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/reservation}Reservation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "floor",
    "number",
    "numberOfBeds",
    "defaultPrice",
    "accommodationUnitType",
    "id",
    "deleted",
    "periodPrices",
    "accommodation",
    "reservations"
})
@XmlRootElement(name = "Accommodation_unit")
@Entity
public class AccommodationUnit {

    @XmlElement(name = "Floor")
    protected int floor;

    @XmlElement(name = "Number", required = true)
    protected String number;

    @XmlElement(name = "Number_of_beds")
    protected int numberOfBeds;

    @XmlElement(name = "Default_price")
    protected Double defaultPrice;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @NotFound(action = NotFoundAction.IGNORE)
    @XmlElement(name = "Accommodation_unit_type", required = true)
    protected AccommodationUnitType accommodationUnitType;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlElement(name = "Id")
    protected long id;

    @XmlElement(name = "Deleted")
    protected boolean deleted;

    @OneToMany(mappedBy = "accommodationUnit", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Period_price")
    protected Set<PeriodPrice> periodPrices;

    @ManyToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Accommodation", required = true)
    protected Accommodation accommodation;

    @OneToMany(mappedBy = "accommodationUnit", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Reservation", required = true)
    protected Set<Reservation> reservations;


    public AccommodationUnit() {

    }

    public AccommodationUnit(int floor, String number, int numberOfBeds, Double defaultPrice) {
        this.floor = floor;
        this.number = number;
        this.numberOfBeds = numberOfBeds;
        this.defaultPrice = defaultPrice;
    }
    /**
     * Gets the value of the floor property.
     * 
     */
    public int getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     */
    public void setFloor(int value) {
        this.floor = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the numberOfBeds property.
     * 
     */
    public int getNumberOfBeds() {
        return numberOfBeds;
    }

    /**
     * Sets the value of the numberOfBeds property.
     * 
     */
    public void setNumberOfBeds(int value) {
        this.numberOfBeds = value;
    }

    /**
     * Gets the value of the defaultPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDefaultPrice() {
        return defaultPrice;
    }

    /**
     * Sets the value of the defaultPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDefaultPrice(Double value) {
        this.defaultPrice = value;
    }

    /**
     * Gets the value of the accommodationUnitType property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationUnitType }
     *     
     */
    public AccommodationUnitType getAccommodationUnitType() {
        return accommodationUnitType;
    }

    /**
     * Sets the value of the accommodationUnitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationUnitType }
     *     
     */
    public void setAccommodationUnitType(AccommodationUnitType value) {
        this.accommodationUnitType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the periodPrices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodPrices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodPrices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodPrice }
     * 
     * 
     */
    public Set<PeriodPrice> getPeriodPrices() {
        if (periodPrices == null) {
            periodPrices = new HashSet<>();
        }
        return this.periodPrices;
    }

    /**
     * Gets the value of the accommodation property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation }
     *     
     */
    public Accommodation getAccommodation() {
        return accommodation;
    }

    /**
     * Sets the value of the accommodation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation }
     *     
     */
    public void setAccommodation(Accommodation value) {
        this.accommodation = value;
    }

    /**
     * Gets the value of the reservations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reservation }
     * 
     * 
     */
    public Set<Reservation> getReservations() {
        if (reservations == null) {
            reservations = new HashSet<>();
        }
        return this.reservations;
    }

}
